name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.1.3
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/openid_client

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  dart_jwt: '>=0.6.0 <0.7.0'
  http: '>=0.11.3+10 <0.12.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  build_runner: '>=0.1.1 <0.2.0'
  browser: '>=0.10.0 <0.11.0'
  angular2: '>=2.0.0 <4.0.0'
  unscripted: '>=0.6.2 <0.7.0'
  source_gen: '>=0.5.3 <0.6.0'

transformers:
executables:
  openid_client: openid_client