name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.3.0
homepage: https://github.com/appsup-dart/openid_client

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  jose: '>=0.1.2 <0.3.0'
  pointycastle: ^1.0.0
  http: ^0.12.0
  logging: ^0.11.3+2
  args: ^1.5.0

dev_dependencies:
  test: ^1.0.0
  angular: ^5.0.0
  build_runner: ^1.6.2
  build_web_compilers: ^2.6.1
  pedantic: ^1.9.0

executables:
  openid_client: openid_client